[package]
name = "testcontainer_wrappers"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
rdkafka = "0.38.0"
testcontainers = "0.25.0"
tokio = { version = "1.47.1", features = ["full"] }
uuid = { version = "1.18.1", features = ["v4"] }
